apiVersion: apps/v1
kind: Deployment
metadata:
  name: skakoui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skakoui
  template:
    metadata:
      labels:
        app: skakoui
    spec:
      containers:
      - name: skakoui
        image: docker.io/aelred/skakoui:master-d14f1724-1633601576 # {"$imagepolicy": "flux-system:skakoui"}
        env:
        - name: LICHESS_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: lichess-api-token
              key: value
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: skakoui
  namespace: flux-system
spec:
  image: docker.io/aelred/skakoui
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: skakoui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: skakoui
  filterTags:
    pattern: '^master-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: skakoui
  namespace: flux-system
spec:
  type: dockerhub
  secretRef:
    name: webhook-token
  resources:
  - kind: ImageRepository
    name: skakoui
---
# lichess-bot seems to disconnect from Lichess within 1-2 days
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: skakoui-periodic-restart
spec:
  concurrencyPolicy: Forbid
  schedule: '@midnight'
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          restartPolicy: Never
          containers:
          - name: kubectl
            image: bitnami/kubectl
            command: ['kubectl', 'rollout', 'restart', 'deployment/skakoui']
