apiVersion: apps/v1
kind: Deployment
metadata:
  name: skakoui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skakoui
  template:
    metadata:
      labels:
        app: skakoui
    spec:
      containers:
      - name: skakoui
        image: docker.io/aelred/skakoui:master-278e9bf6-1614990915 # {"$imagepolicy": "flux-system:skakoui"}
        env:
        - name: LICHESS_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: lichess-api-token
              key: value
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: skakoui
  namespace: flux-system
spec:
  image: docker.io/aelred/skakoui
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: skakoui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: skakoui
  filterTags:
    pattern: '^master-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: skakoui
  namespace: flux-system
spec:
  type: dockerhub
  secretRef:
    name: webhook-token
  resources:
  - kind: ImageRepository
    name: skakoui
