apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris-server
  template:
    metadata:
      labels:
        app: tetris-server
    spec:
      containers:
      - name: tetris-server
        image: aelred/tetris-server:0f25a4dea6974b2cce79312728e5b16d3f991b84
        env:
          - name: ROCKET_PORT
            value: "80"
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tetris-server
spec:
  rules:
    - host: api.tetris.ael.red
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: tetris-server
                port:
                  number: 80
