apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tetris-server
  template:
    metadata:
      labels:
        app: tetris-server
    spec:
      containers:
      - name: tetris-server
        image: aelred/tetris-server:0f25a4dea6974b2cce79312728e5b16d3f991b84
        env:
          - name: ROCKET_PORT
            value: "8000"
        ports:
        - containerPort: 8000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-server
spec:
  selector:
    app: tetris-server
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tetris-server
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: api.tetris.ael.red
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: tetris-server
                port:
                  number: 8000
