apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: tetris
  namespace: default
spec:
  url: https://github.com/aelred/tetris
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tetris
  namespace: default
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: tetris
  path: ./deploy/manifests
  images:
    - name: docker.io/aelred/tetris-server
      newTag: master-f6c70e30-1641674177 # {"$imagepolicy": "flux-system:tetris-server:tag"}
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: tetris-server
  namespace: flux-system
spec:
  image: docker.io/aelred/tetris-server
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: tetris-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: tetris-server
  filterTags:
    pattern: '^master-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: tetris-server
  namespace: flux-system
spec:
  type: dockerhub
  secretRef:
    name: webhook-token
  resources:
    - kind: ImageRepository
      name: tetris-server
