apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: skakoui
  namespace: default
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: kustomizations
  path: ./kustomizations/service
  postBuild:
    substitute:
      name: skakoui
      image: skakoui
      tag: latest # {"": "flux-system:skakoui:tag"}