apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tetris
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: kustomizations
  path: ./kustomizations/service
  postBuild:
    substitute:
      name: tetris
      image: tetris-server
      tag: master-94618560-1641929592 # {"$imagepolicy": "flux-system:tetris:tag"}