apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  dataDirHostPath: /storage
  placement:
    all:
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Equal
          effect: NoSchedule
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.7
  mon:
    count: 3
    allowMultiplePerNode: false
  storage:
    useAllNodes: true
    deviceFilter: vdb
    config:
      databaseSizeMB: "1024"
      journalSizeMB: "1024"
