# Add webhook receiver for the manifests repo itself, so flux is notified on push
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: manifests-github
  namespace: flux-system
spec:
  events:
  - ping
  - push
  resources:
  - kind: GitRepository
    name: flux-system
  secretRef:
    name: manifests-github-webhook-token
  type: github
