apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ${name}
  namespace: flux-system
spec:
  url: https://github.com/aelred/${name}
  interval: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ${name}-repo
  namespace: flux-system
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: ${name}
  path: ./deploy/manifests
  images:
    - name: docker.io/aelred/${name}
      newTag: ${tag}
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: ${name}
  namespace: flux-system
spec:
  image: docker.io/aelred/${name}
  interval: 1m0s
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: ${name}
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ${name}
  filterTags:
    pattern: '^master-[a-fA-F0-9]+-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: ${name}-dockerhub
  namespace: flux-system
spec:
  type: dockerhub
  secretRef:
    name: webhook-token
  resources:
    - kind: ImageRepository
      name: ${name}
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: ${name}-github
  namespace: flux-system
spec:
  type: github
  secretRef:
    name: github-${name}-webhook-token
  resources:
    - kind: GitRepository
      name: ${name}
    - kind: Kustomization
      name: ${name}-repo
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: ${name}
  namespace: flux-system
spec:
  type: github
  address: https://github.com/aelred/${name}
  secretRef:
    name: github-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: ${name}
  namespace: flux-system
spec:
  providerRef:
    name: ${name}
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: ${name}-repo
